"""notes

Revision ID: 36b04173c8da
Revises: 550d47d488d9
Create Date: 2024-09-01 04:34:14.485397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b04173c8da'
down_revision: Union[str, None] = '550d47d488d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notes',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_index(op.f('ix_Notes_user_id'), 'Notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notes_user_id'), table_name='Notes')
    op.drop_table('Notes')
    # ### end Alembic commands ###
